name: Memory Error Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install GCC
      run: sudo apt-get install gcc -y
    - name: Build with Address Sanitizer
      run: gcc -fsanitize=address -o my_program my_program.c
    - name: Run the program
      run: ./my_program
